RIVA_MOUNTED_DATA_DIR='/data'
RIVA_MOUNTED_SPECS_DIR='/specs'
RIVA_MOUNTED_RESULTS_DIR='/results'
DOMAIN=<your domain i.e. field of focus for the queries>
LOCAL_RESULT_DIR=<local results folder>
RIVA_REPO="path/to/riva_quickstart_v1.10.0-beta"
RIVA_SERVICE_MAKER=nvcr.io/nvidia/riva/riva-speech:1.10.0-beta-servicemaker
NUM_CLASSES=<number of intents in training set>
NUM_EPOCH=500
NGC_API_KEY=<Your NGC API Key>
ENCRYPTION_KEY="tlt_encode"
GPUS=1
